-- LISTING STORED PROCEDURES
-- GENERAL SYNTAX : SHOW PROCEDURE STATUS [ LIKE pattern | WHERE search_condition]

SHOW PROCEDURE STATUS;

SHOW PROCEDURE STATUS
WHERE db = 'classicmodels';

SHOW PROCEDURE STATUS
LIKE '%Count%';



 